services:
    redis:
        image: redis:7-alpine
        # restart: always
        ports:
            - "6379:6379"
        command: redis-server --appendonly no --save "" --loglevel warning
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 3
    engine:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/app/code
        environment:
            - REDIS_URL=redis://redis:6379/?dial_timeout=5s&max_retries=3
            - LISTEN_ADDRESS=0.0.0.0:8080
            - ENV=dev
        depends_on:
            redis:
                condition: service_healthy
